# tasks file
---
- name: include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  when: sudoers_include_variables | bool
  tags:
    - configuration
    - sudoers
    - sudoers-include-variables

- name: install
  ansible.builtin.apt:
    name: "{{ sudoers_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  when: sudoers_install | bool
  tags:
    - configuration
    - sudoers
    - sudoers-install

- name: update /etc/sudoers.d directory permissions
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    owner: root
    group: root
    mode: "{{ sudoers_sudoers_d_directory_mode }}"
  when: sudoers_sudoers_d_directory_mode is defined
  tags:
    - configuration
    - sudoers
    - sudoers-configuration
    - sudoers-configuration-sudoers-d

- name: update specific configuration files
  ansible.builtin.template:
    src: etc/sudoers.d/sudoers.j2
    dest: "/etc/sudoers.d/{{ item.key }}"
    validate: "visudo -cf %s"
    owner: root
    group: root
    mode: 0440
  with_dict: "{{ sudoers_sudoers_d_files }}"
  when: sudoers_configuration_sudoers_d | bool
  tags:
    - configuration
    - sudoers
    - sudoers-configuration
    - sudoers-configuration-sudoers-d

- name: update global configuration file
  ansible.builtin.template:
    src: etc/sudoers.j2
    dest: /etc/sudoers
    validate: "visudo -cf %s"
    owner: root
    group: root
    mode: 0440
  when: sudoers_configuration_sudoers | bool
  tags:
    - configuration
    - sudoers
    - sudoers-configuration
    - sudoers-configuration-sudoers
